markdown: kramdown
url: https://winstonhoseadriggins.github.io
gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
collections:
  portfolio:
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
permalink: /blogs/:year/:month/:day/:title/
baseurl: /DW84IncLLC
exclude: ['Readme.md']